spring.application.name=demo1

# LM Studio 0.4.9+ OpenAI/api?
spring.ai.openai.base-url=http://172.27.96.1:1234

#spring.ai.openai.api-key=sk-lm-n9VCMAGV:jZXZhKwVOzene1haw7re

spring.ai.openai.api-key=lmstudio
# LM Studio API Identifier
#spring.ai.openai.chat.model=deepseek-r1-distill-qwen-14b
#spring.ai.openai.chat.model=google/gemma-3-4b
spring.ai.openai.chat.model=qwen3.5-2b


spring.ai.openai.chat.connect-timeout=120s
spring.ai.openai.chat.read-timeout=300s
spring.ai.openai.chat.options.maxTokens=4096

spring.ai.openai.chat.options.temperature=0.5

# Spring AI:JDBC
spring.ai.chat.memory.repository.jdbc.initialize-schema=always

# MySQL CONFIG
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/springai?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false&allowMultiQueries=true
spring.autoconfigure.exclude=org.springframework.ai.model.chat.memory.repository.jdbc.autoconfigure.JdbcChatMemoryRepositoryAutoConfiguration
spring.datasource.username=root
spring.datasource.password=root
